#!/usr/bin/env python
import logging
import sys
import BaseHTTPServer
import SimpleHTTPServer


class MyHTTPRequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def log_message(self, format, *args):
        pass


HandlerClass = MyHTTPRequestHandler
ServerClass  = BaseHTTPServer.HTTPServer
Protocol     = "HTTP/1.0"

if sys.argv[1:]:
    listenAddr = sys.argv[1]
    if ':' in listenAddr:
        addr, port = listenAddr.split(':', 1)
        port = int(port)
    else:
        addr = '127.0.0.1'
        port = int(listenAddr)
else:
    addr = '127.0.0.1'
    port = 8081

server_address = (addr, port)

HandlerClass.protocol_version = Protocol
httpd = ServerClass(server_address, HandlerClass)

sa = httpd.socket.getsockname()
print "Serving HTTP on", sa[0], "port", sa[1], "..."
logging.disable(logging.CRITICAL)
try:
    httpd.serve_forever()
except KeyboardInterrupt:
    pass
