#!/bin/bash
function trim ()
{
    local var="$@"
    var="${var#"${var%%[![:space:]]*}"}"
    var="${var%"${var##*[![:space:]]}"}"
    echo -n "$var"
}

function update_repo ()
{
	local repo_path=$(echo -n "$1" | sed -e "s|~|$HOME|")
	if test ! -d "$repo_path" ; then
		return 0
	fi

	if test ! -d "$repo_path/.git" ; then
		return 0
	fi

	echo "Updating $repo_path..."
	local curDir=$(pwd)
	cd "$repo_path" && git ffwd
	cd "$curDir"
}

update_repo ~/.vim
update_repo ~/.vimuser
update_repo ~/.etc
update_repo ~/.ssh
update_repo ~/projects/etc
update_repo ~/projects/jszakmeister/local-homepage
update_repo ~/projects/local-homepage

if test -f ~/.update-commonrc ; then
    while read line
    do
        line=$(trim "$line")

        if [ -n "$line" ] && [[ $line != \#* ]] ; then
            update_repo "$line"
        fi
    done < ~/.update-commonrc
fi
