#!/bin/bash

if test -z "$1"; then
	echo "You must provide a source for the links." >&2
	exit 1
fi

SOURCE="${1/\/%/}"
SOURCE_LENGTH=$(( ${#SOURCE} + 1 ))

find -L "$SOURCE" -type f | while read LINK; do
    TARGET=${LINK:$SOURCE_LENGTH}
    echo ln -sf "$LINK" "$TARGET"
    ln -sf "$LINK" "$TARGET"
done
