#!/bin/bash
function find_tags
{
    local last_found=$(pwd)
    local tmp_path=$(pwd)
    while [[ "$tmp_path" != "/" ]];
    do
        if [ -e "$tmp_path/tags" ]; then
            echo "$tmp_path"
            break
        fi
        tmp_path=$(dirname "$tmp_path")
    done
}


function die
{
    echo 1>&2 "ERROR: $1"
    exit 1
}


if test -n "$1"
then
    while [ "$1" != "" ]
    do
        case $1 in
            --init)
                tag_dir="$2"
                shift
                ;;
            -o)
                output_path="$2"
                shift
                ;;
            *)
                die "Unknown option: $1"
                ;;
        esac
        shift
    done
fi

if [ -z "$tag_dir" ]; then
    tag_dir="$(find_tags)"
fi

if [ "$tag_dir" == "" ]; then
    die "No tag directory found."
fi

if [ -z "$output_path" ]; then
    output_path="$tag_dir/tags"
fi

ctags -R --exclude=build \
         --exclude=dist \
         --exclude=_build \
         --exclude=__pycache__ \
         --exclude='.[a-z]*' \
         --exclude=classes \
         --exclude='lusty-explorer.vim' \
         --exclude='lusty-juggler.vim' \
         --exclude='*.gz' \
         --exclude='*.bz2' \
         --exclude='*.xz' \
         --exclude='*.snippets' \
         --langmap="vim:+(vimrc)" \
         --c-kinds=+px \
         --c++-kinds=+px \
         --fields=+iaS \
         --extra=+qf \
         -o "$output_path" \
         "$tag_dir/" || die "Error executing ctags"
