#!/bin/bash
find_tags()
{
    local last_found=$(pwd)
    local tmp_path=$(pwd)
    while [[ "$tmp_path" != "/" ]];
    do
        if [ -e "$tmp_path/tags" ]; then
            echo "$tmp_path"
            break
        fi
        tmp_path=$(dirname "$tmp_path")
    done
}


die()
{
    echo 1>&2 "ERROR: $1"
    exit 1
}


if test -n "$1"
then
    while [ "$1" != "" ]
    do
        case $1 in
            --init)
                tag_dir="$2"
                shift
                ;;
            -o)
                output_path="$2"
                shift
                ;;
            -*)
                die "Unknown option: $1"
                ;;
            *)
                # The rest should be paths.
                break
                ;;
        esac
        shift
    done
fi

if [ -z "$tag_dir" ]; then
    tag_dir="$(find_tags)"
fi

if [ "$tag_dir" == "" ]; then
    die "No tag directory found."
fi

if [ -z "$output_path" ]; then
    output_path="$tag_dir/tags"
fi

ctags -R --exclude=build \
         --exclude=dist \
         --exclude=venv \
         --exclude=_build \
         --exclude=__pycache__ \
         --exclude=static \
         --exclude=node_modules \
         --exclude=export \
         --exclude=pkgexp \
         --exclude='.[a-z]*' \
         --exclude=classes \
         --exclude='lusty-explorer.vim' \
         --exclude='lusty-juggler.vim' \
         --exclude='*.gz' \
         --exclude='*.bz2' \
         --exclude='*.xz' \
         --exclude='*.snippets' \
         --exclude='*.min.js' \
         --langmap="vim:+(vimrc)" \
         --c-kinds=+px \
         --c++-kinds=+px \
         --fields=+iaS \
         --extras=+qf \
         -I FUNC_ATTR_MALLOC \
         -I FUNC_ATTR_ALLOC_SIZE+ \
         -I FUNC_ATTR_ALLOC_SIZE_PROD+ \
         -I FUNC_ATTR_ALLOC_ALIGN+ \
         -I FUNC_ATTR_PURE \
         -I FUNC_ATTR_CONST \
         -I FUNC_ATTR_WARN_UNUSED_RESULT \
         -I FUNC_ATTR_ALWAYS_INLINE \
         -I FUNC_ATTR_UNUSED \
         -I FUNC_ATTR_NONNULL_ALL \
         -I FUNC_ATTR_NONNULL_ARG+ \
         -I FUNC_ATTR_NONNULL_RET \
         -o "$output_path" \
         "$tag_dir/" "$@" || die "Error executing ctags"
