#!/bin/bash
OS=$(uname | tr '[A-Z]' '[a-z]')

if [[ "$OS" != "linux" && "$OS" != "darwin" ]]; then
    echo "Unrecognized OS" >& 2
    exit 1
fi

extraopts=""
if [[ "$OS" == "linux" ]]; then
    extraopts="--name GVIM0"

    type -a wmctrl 2>&1 > /dev/null || {
        echo 2>&1 "ERROR: please install wmctrl" ;
        exit 1 ;
    }
fi

if [[ "$OS" == "darwin" ]]; then
    running=$(ps x | grep MacVim | grep GVIM0)
    ETC_GR_SLEEP_TIME=${ETC_GR_SLEEP_TIME:-3}
else
    running=$(ps -f | grep gvim | grep GVIM0)
    ETC_GR_SLEEP_TIME=${ETC_GR_SLEEP_TIME:-1}
fi

if [[ -z "$running" ]]; then
    gvim $extraopts --servername GVIM0 || exit 1
    sleep $ETC_GR_SLEEP_TIME
fi

if [[ -n "$@" ]]; then
    gvim $extraopts --servername GVIM0 --remote-silent "$@"
fi

if [[ "$OS" == "darwin" ]]; then
    if [[ -n "$running" ]]; then
        echo 'tell application "System Events" to set frontmost of process "MacVim" to true' | osascript
    fi
elif [[ "$OS" == "linux" ]]; then
    wmctrl -xa GVIM0.Gvim
fi
