#!/bin/bash
OS=$(uname | tr '[A-Z]' '[a-z]')

if [[ "$OS" != "linux" && "$OS" != "darwin" ]]; then
    echo "Unrecognized OS" >& 2
    exit 1
fi

if [[ "$OS" == "darwin" && -z "$SECURITYSESSIONID" ]]; then
    echo >&2 "No GUI available"
    exit 1
fi

if [[ -n "$SSH_TTY" ]]; then
    SERVER_NAME="GVIM1"
else
    SERVER_NAME="GVIM0"
fi

extraopts=""
if [[ "$OS" == "linux" ]]; then
    extraopts="--name $SERVER_NAME"

    type -a wmctrl > /dev/null 2>&1 || {
        echo 2>&1 "ERROR: please install wmctrl" ;
        exit 1 ;
    }
fi

running=$(gvim --serverlist | grep $SERVER_NAME)

if [[ -n "$@" ]]; then
    gvim $extraopts --servername $SERVER_NAME --remote-silent "$@"
elif [[ -z "$running" ]]; then
    gvim $extraopts --servername $SERVER_NAME
fi

if [[ "$OS" == "darwin" ]]; then
    if [[ -n "$running" ]]; then
        echo 'tell application "System Events" to set frontmost of process "MacVim" to true' | osascript
    fi
elif [[ "$OS" == "linux" ]]; then
    wmctrl -xa $SERVER_NAME.Gvim
fi
