#!/usr/bin/env python3
import sys
import re


for arg in sys.argv[1:]:
    with open(arg, 'r+b') as f:
        buf = f.read()
        buf = re.sub(rb'\r?\n', rb'\n', buf)
        f.seek(0)
        f.write(buf)
        f.truncate()
