#!/usr/bin/env python

import sys, os, re

if len(sys.argv) < 2 or len(sys.argv) > 3:
  print "Usage: %s <size in MB> [volume name]"
  sys.exit(1)

size_in_mb = long(sys.argv[1])
if size_in_mb < 4:
  print "The RAM disk must be at least 4 MB in size"
  sys.exit(1)

if len(sys.argv) == 2:
  volume_name = "Untitled"
else:
  volume_name = sys.argv[2]

# convert size into number of 512K blocks.
size = size_in_mb * 2048

print "Allocating %d blocks" % size
dev_re = re.compile(r'/dev/(.*)')
output = os.popen4('hdid -nomount ram://%d' % size)[1].read()
m = dev_re.match(output)
if not m:
  print "hdid failed with:\n%s" % output
disk_name = m.group(1)
print "Creating HFS Plus filesystem on %s" % disk_name
output = os.popen4('diskutil partitionDisk %s 1 HFS+ "%s" %dM' % (disk_name, volume_name, size_in_mb))[1].read()
print output
print "Mounting %s" % disk_name
output = os.popen4('hdiutil mount /dev/%s' % disk_name)[1].read()
print output
