#!/bin/sh

SUBDIRECTORY_OK=1 . "$(git --exec-path)/git-sh-setup" ||
    die "Not a git repository."

test -t 1 && color=t

if [ -n "$color" ]
then
    command -v colordiff > /dev/null || color=
fi

function do_interdiff_branches()
{
    local merge_base = "$(git merge-base "$1" "$2")"

    # git -c color.ui=off diff $(git merge-base master "$1") "$1" > "$GIT_DIR/commit1" &&
    #     git -c color.ui=off diff $(git merge-base master "$2") "$2" > "$GIT_DIR/commit2" &&
    git -c color.ui=off diff "$merge_base" "$1" > "$GIT_DIR/commit1" &&
        git -c color.ui=off diff "$merge_base" "$2" > "$GIT_DIR/commit2" &&
        (
            echo interdiff --no-revert-omitted "$GIT_DIR"/commit{1,2}
            interdiff "$GIT_DIR"/commit{1,2} |
            (
                test -n "$color" && { colordiff | diff-highlight ; } || cat -
            )
        )
}

do_interdiff_branches "$@" | git_pager
