#!/bin/bash
SUBDIRECTORY_OK=1 source "$(git --exec-path)/git-sh-setup" ||
    die "ERROR: Not a git repository."

DRY_RUN=

if [ "$1" = "-n" ]
then
    DRY_RUN=echo
fi

REF="$(git symbolic-ref --short HEAD)"

case "$REF" in
    master)
        ;;
    develop)
        ;;
    development)
        ;;
    *)
        die "ERROR: Not on an acceptable branch (master, develop, development)"
        ;;
esac

git branch -r --merged "$REF" |
    egrep -v '^(\* |[ \t]*)[^/]*/([0-9]+\.[0-9]+\.x|master|main|develop|development|HEAD( -> .*)|integrate)$' |
    egrep -v "$REF" |
    while read -r line
    do
        echo "$line" | sed -e 's|/| :|' | xargs -n 2 ${DRY_RUN} git push
    done
