ETC_HOME=${ETC_HOME:-~/projects/etc}

export ETC_ZSHENV_SOURCED=1

# Set up a few options.  Mainly to keep warnings from being
# emitted... as that would break the output of non-interactive
# scripting environments.
setopt case_glob            # case sensitive globbing
setopt clobber              # redirection can create files
setopt glob		    # want globbing
unsetopt nomatch	    # don't warn about non-matching globs
setopt pushd_silent         # don't print stack after push/pop

# A function to help with creating directory aliases and providing
# completion for them.
# Taken from here:
#   https://github.com/caio/oh-my-zsh/blob/master/plugins/make-dir-complete/make-dir-complete.plugin.zsh
_make_dir_complete() {
    if [ ${#} -ne 2 ]; then
        echo "usage: make_dir_complete <new-alias-name> <path>" 1>&2
        return 1
    fi

    local aliasname=$1

    if type $aliasname >/dev/null 2>&1; then
        echo "Error: can't overwrite previously defined command \"$1\"" 1>&2
        return 1
    fi
    if [ ! -d $2 ]; then
        echo "Error: \"$2\" doesn't point to a directory" 1>&2
    fi

    cd "$2" >/dev/null 2>&1
    local dirname=$(pwd -L)
    cd - >/dev/null 2>&1

    FUNC="$aliasname () { cd $dirname/\$@ }"
    eval $FUNC
    compctl -/ -W $dirname $aliasname
}

test -s "$ETC_HOME/shell-common/functions.sh" &&
	. $ETC_HOME/shell-common/functions.sh
test -s "$ETC_HOME/shell-common/exports.sh" &&
	. "$ETC_HOME/shell-common/exports.sh"
