ETC_HOME=${ETC_HOME:-~/projects/etc}

test -s "$ETC_HOME/zsh/shell-options.zsh" &&
	. "$ETC_HOME/zsh/shell-options.zsh"

test -s "$ETC_HOME/shell-common/functions.sh" &&
	. $ETC_HOME/shell-common/functions.sh
test -s "$ETC_HOME/shell-common/exports.sh" &&
	. "$ETC_HOME/shell-common/exports.sh"
test -s "$ETC_HOME/shell-common/aliases.sh" &&
	. "$ETC_HOME/shell-common/aliases.sh"

# add a function path
fpath=("$ETC_HOME/zsh/functions" "$ETC_HOME/zsh/completions" $fpath)

# Load all of the config files in ~/oh-my-zsh that end in .zsh
# TIP: Add files you don't want in git to .gitignore
for config_file ($ETC_HOME/zsh/lib/*.zsh) source $config_file

source "$ETC_HOME/zsh/themes/${ZSH_THEME:-jszakmeister}.zsh-theme"

