ETC_HOME="${ETC_HOME:-$HOME/projects/etc}"
ETC_USER="${ETC_USER:-$(whoami)}"

_start_ansi='%{'
_end_ansi='%}'

. "$ETC_HOME/zsh/shell-options.zsh"

# If the user setup ~/.zshenv, and sourced our zshenv,
# then we want to avoid sourcing a couple of scripts
# again.  That's especially true for exports.sh, since
# it'll modify the path variables again.
if [[ -z "$ETC_ZSHENV_SOURCED" ]]; then
	. "$ETC_HOME/zsh/zshenv"
fi

. "$ETC_HOME/shell-common/interactive.sh"

# add a function path
fpath=("$ETC_HOME/zsh/functions" "$ETC_HOME/zsh/completions" $fpath)

for config_file ($ETC_HOME/zsh/lib/*.zsh) source $config_file

source "$ETC_HOME/zsh/themes/${ZSH_THEME:-jszakmeister}.zsh-theme"

test -f "$ETC_HOME/user/$ETC_USER/init.sh" &&
	. "$ETC_HOME/user/$ETC_USER/init.sh"

test -f "$HOME/.etcrc" && . "$HOME/.etcrc"
